
package dk.semler.ws.vehiclesalecalculator.v201412.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XMLService200903", targetNamespace = "http://www.semlernet.dk/xmlns/xmlservice/200903/", wsdlLocation = "file:/C:/ng/ws/PriceAdapter.v201710.Web/WebContent/WEB-INF/client/VehicleSaleCalculator.v201412.wsdl")
public class XMLService200903
    extends Service
{

    private final static URL XMLSERVICE200903_WSDL_LOCATION;
    private final static WebServiceException XMLSERVICE200903_EXCEPTION;
    private final static QName XMLSERVICE200903_QNAME = new QName("http://www.semlernet.dk/xmlns/xmlservice/200903/", "XMLService200903");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/ng/ws/PriceAdapter.v201710.Web/WebContent/WEB-INF/client/VehicleSaleCalculator.v201412.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XMLSERVICE200903_WSDL_LOCATION = url;
        XMLSERVICE200903_EXCEPTION = e;
    }

    public XMLService200903() {
        super(__getWsdlLocation(), XMLSERVICE200903_QNAME);
    }

    public XMLService200903(WebServiceFeature... features) {
        super(__getWsdlLocation(), XMLSERVICE200903_QNAME, features);
    }

    public XMLService200903(URL wsdlLocation) {
        super(wsdlLocation, XMLSERVICE200903_QNAME);
    }

    public XMLService200903(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XMLSERVICE200903_QNAME, features);
    }

    public XMLService200903(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XMLService200903(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns XMLService
     */
    @WebEndpoint(name = "XMLService200903SOAP")
    public XMLService getXMLService200903SOAP() {
        return super.getPort(new QName("http://www.semlernet.dk/xmlns/xmlservice/200903/", "XMLService200903SOAP"), XMLService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XMLService
     */
    @WebEndpoint(name = "XMLService200903SOAP")
    public XMLService getXMLService200903SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.semlernet.dk/xmlns/xmlservice/200903/", "XMLService200903SOAP"), XMLService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XMLSERVICE200903_EXCEPTION!= null) {
            throw XMLSERVICE200903_EXCEPTION;
        }
        return XMLSERVICE200903_WSDL_LOCATION;
    }

}
