
package dk.semler.ws.vehiclesalecalculator.v201412.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XMLService", targetNamespace = "http://www.semlernet.dk/xmlns/xmlservice/200903/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XMLService {


    /**
     * 
     * @param parameters
     * @return
     *     returns dk.semler.ws.vehiclesalecalculator.v201412.stubs.ExecuteServiceResponse
     */
    @WebMethod(operationName = "ExecuteService", action = "http://www.semlernet.dk/xmlns/XMLService/200903/ExecuteService")
    @WebResult(name = "ExecuteServiceResponse", targetNamespace = "http://www.semlernet.dk/xmlns/types/xmlservice/200903/", partName = "parameters")
    public ExecuteServiceResponse executeService(
        @WebParam(name = "ExecuteServiceRequest", targetNamespace = "http://www.semlernet.dk/xmlns/types/xmlservice/200903/", partName = "parameters")
        ExecuteServiceRequest parameters);

}
