//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 12:09:56 PM PKT 
//


package dk.semler.ws.vehiclesalecalculator.v201412.calculatenewvehicle.response;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			
 * 			
 * 
 * <p>Java class for CALCULATIONType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CALCULATIONType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DEALERPRICE"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DEALERMARGIN" type="{}PRICEType"/&gt;
 *         &lt;element name="SALESPRICE" type="{}PRICEType"/&gt;
 *         &lt;element name="TOTALPRICE" type="{}PRICEType"/&gt;
 *         &lt;element name="VEHICLESOLDTODEALERPRICE"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="VEHICLESOLDTODEALERTOTALPRICE"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CUSTOMERDISCOUNT"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="GRANDTOTALPRICE" type="{}PRICEType"/&gt;
 *         &lt;element name="DEALERMAXDISCOUNT"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MINIMUMSTANDARDPRICETOTAL" type="{}PRICEType"/&gt;
 *         &lt;element name="SECURITYEQUIPMENTDISCOUNT"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FUELREGULATION"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TAXEXCLREGULATIONS"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TAXEXCLREGULATIONSEXCLEQUIPMENT"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FACTORYEQUIPMENTTOTALPRICE" type="{}PRICEType"/&gt;
 *         &lt;element name="STANDARDEQUIPMENTTOTALPRICE" type="{}PRICEType"/&gt;
 *         &lt;element name="IMPORTERDEFINEDDEALEREQUIPMENTTOTALPRICE" type="{}PRICEType"/&gt;
 *         &lt;element name="IMPORTERDEFINEDDEALEREQUIPMENTTOTALLISTPRICE"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DEALEREQUIPMENTTOTALPRICE" type="{}PRICEType"/&gt;
 *         &lt;element name="EQUIPMENTPROVIDEDBYFACTORYTOTALPRICE" type="{}PRICEType"/&gt;
 *         &lt;element name="EQUIPMENTPROVIDEDBYDEALERTOTALPRICE" type="{}PRICEType"/&gt;
 *         &lt;element name="TOTALVEHICLEPRICE" type="{}PRICEType"/&gt;
 *         &lt;element name="DEALERMARGINEXCLEQUIPMENT" type="{}PRICEType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CALCULATIONType", propOrder = {
    "dealerprice",
    "dealermargin",
    "salesprice",
    "totalprice",
    "vehiclesoldtodealerprice",
    "vehiclesoldtodealertotalprice",
    "customerdiscount",
    "grandtotalprice",
    "dealermaxdiscount",
    "minimumstandardpricetotal",
    "securityequipmentdiscount",
    "fuelregulation",
    "taxexclregulations",
    "taxexclregulationsexclequipment",
    "factoryequipmenttotalprice",
    "standardequipmenttotalprice",
    "importerdefineddealerequipmenttotalprice",
    "importerdefineddealerequipmenttotallistprice",
    "dealerequipmenttotalprice",
    "equipmentprovidedbyfactorytotalprice",
    "equipmentprovidedbydealertotalprice",
    "totalvehicleprice",
    "dealermarginexclequipment"
})
public class CALCULATIONType {

    @XmlElement(name = "DEALERPRICE", required = true)
    protected BigDecimal dealerprice;
    @XmlElement(name = "DEALERMARGIN", required = true)
    protected PRICEType dealermargin;
    @XmlElement(name = "SALESPRICE", required = true)
    protected PRICEType salesprice;
    @XmlElement(name = "TOTALPRICE", required = true)
    protected PRICEType totalprice;
    @XmlElement(name = "VEHICLESOLDTODEALERPRICE", required = true)
    protected BigDecimal vehiclesoldtodealerprice;
    @XmlElement(name = "VEHICLESOLDTODEALERTOTALPRICE", required = true)
    protected BigDecimal vehiclesoldtodealertotalprice;
    @XmlElement(name = "CUSTOMERDISCOUNT", required = true)
    protected BigDecimal customerdiscount;
    @XmlElement(name = "GRANDTOTALPRICE", required = true)
    protected PRICEType grandtotalprice;
    @XmlElement(name = "DEALERMAXDISCOUNT", required = true)
    protected BigDecimal dealermaxdiscount;
    @XmlElement(name = "MINIMUMSTANDARDPRICETOTAL", required = true)
    protected PRICEType minimumstandardpricetotal;
    @XmlElement(name = "SECURITYEQUIPMENTDISCOUNT", required = true)
    protected BigDecimal securityequipmentdiscount;
    @XmlElement(name = "FUELREGULATION", required = true)
    protected BigDecimal fuelregulation;
    @XmlElement(name = "TAXEXCLREGULATIONS", required = true)
    protected BigDecimal taxexclregulations;
    @XmlElement(name = "TAXEXCLREGULATIONSEXCLEQUIPMENT", required = true)
    protected BigDecimal taxexclregulationsexclequipment;
    @XmlElement(name = "FACTORYEQUIPMENTTOTALPRICE", required = true)
    protected PRICEType factoryequipmenttotalprice;
    @XmlElement(name = "STANDARDEQUIPMENTTOTALPRICE", required = true)
    protected PRICEType standardequipmenttotalprice;
    @XmlElement(name = "IMPORTERDEFINEDDEALEREQUIPMENTTOTALPRICE", required = true)
    protected PRICEType importerdefineddealerequipmenttotalprice;
    @XmlElement(name = "IMPORTERDEFINEDDEALEREQUIPMENTTOTALLISTPRICE", required = true)
    protected BigDecimal importerdefineddealerequipmenttotallistprice;
    @XmlElement(name = "DEALEREQUIPMENTTOTALPRICE", required = true)
    protected PRICEType dealerequipmenttotalprice;
    @XmlElement(name = "EQUIPMENTPROVIDEDBYFACTORYTOTALPRICE", required = true)
    protected PRICEType equipmentprovidedbyfactorytotalprice;
    @XmlElement(name = "EQUIPMENTPROVIDEDBYDEALERTOTALPRICE", required = true)
    protected PRICEType equipmentprovidedbydealertotalprice;
    @XmlElement(name = "TOTALVEHICLEPRICE", required = true)
    protected PRICEType totalvehicleprice;
    @XmlElement(name = "DEALERMARGINEXCLEQUIPMENT", required = true)
    protected PRICEType dealermarginexclequipment;

    /**
     * Gets the value of the dealerprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDEALERPRICE() {
        return dealerprice;
    }

    /**
     * Sets the value of the dealerprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDEALERPRICE(BigDecimal value) {
        this.dealerprice = value;
    }

    /**
     * Gets the value of the dealermargin property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getDEALERMARGIN() {
        return dealermargin;
    }

    /**
     * Sets the value of the dealermargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setDEALERMARGIN(PRICEType value) {
        this.dealermargin = value;
    }

    /**
     * Gets the value of the salesprice property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getSALESPRICE() {
        return salesprice;
    }

    /**
     * Sets the value of the salesprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setSALESPRICE(PRICEType value) {
        this.salesprice = value;
    }

    /**
     * Gets the value of the totalprice property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getTOTALPRICE() {
        return totalprice;
    }

    /**
     * Sets the value of the totalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setTOTALPRICE(PRICEType value) {
        this.totalprice = value;
    }

    /**
     * Gets the value of the vehiclesoldtodealerprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVEHICLESOLDTODEALERPRICE() {
        return vehiclesoldtodealerprice;
    }

    /**
     * Sets the value of the vehiclesoldtodealerprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVEHICLESOLDTODEALERPRICE(BigDecimal value) {
        this.vehiclesoldtodealerprice = value;
    }

    /**
     * Gets the value of the vehiclesoldtodealertotalprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVEHICLESOLDTODEALERTOTALPRICE() {
        return vehiclesoldtodealertotalprice;
    }

    /**
     * Sets the value of the vehiclesoldtodealertotalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVEHICLESOLDTODEALERTOTALPRICE(BigDecimal value) {
        this.vehiclesoldtodealertotalprice = value;
    }

    /**
     * Gets the value of the customerdiscount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCUSTOMERDISCOUNT() {
        return customerdiscount;
    }

    /**
     * Sets the value of the customerdiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCUSTOMERDISCOUNT(BigDecimal value) {
        this.customerdiscount = value;
    }

    /**
     * Gets the value of the grandtotalprice property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getGRANDTOTALPRICE() {
        return grandtotalprice;
    }

    /**
     * Sets the value of the grandtotalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setGRANDTOTALPRICE(PRICEType value) {
        this.grandtotalprice = value;
    }

    /**
     * Gets the value of the dealermaxdiscount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDEALERMAXDISCOUNT() {
        return dealermaxdiscount;
    }

    /**
     * Sets the value of the dealermaxdiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDEALERMAXDISCOUNT(BigDecimal value) {
        this.dealermaxdiscount = value;
    }

    /**
     * Gets the value of the minimumstandardpricetotal property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getMINIMUMSTANDARDPRICETOTAL() {
        return minimumstandardpricetotal;
    }

    /**
     * Sets the value of the minimumstandardpricetotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setMINIMUMSTANDARDPRICETOTAL(PRICEType value) {
        this.minimumstandardpricetotal = value;
    }

    /**
     * Gets the value of the securityequipmentdiscount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSECURITYEQUIPMENTDISCOUNT() {
        return securityequipmentdiscount;
    }

    /**
     * Sets the value of the securityequipmentdiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSECURITYEQUIPMENTDISCOUNT(BigDecimal value) {
        this.securityequipmentdiscount = value;
    }

    /**
     * Gets the value of the fuelregulation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFUELREGULATION() {
        return fuelregulation;
    }

    /**
     * Sets the value of the fuelregulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFUELREGULATION(BigDecimal value) {
        this.fuelregulation = value;
    }

    /**
     * Gets the value of the taxexclregulations property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTAXEXCLREGULATIONS() {
        return taxexclregulations;
    }

    /**
     * Sets the value of the taxexclregulations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTAXEXCLREGULATIONS(BigDecimal value) {
        this.taxexclregulations = value;
    }

    /**
     * Gets the value of the taxexclregulationsexclequipment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTAXEXCLREGULATIONSEXCLEQUIPMENT() {
        return taxexclregulationsexclequipment;
    }

    /**
     * Sets the value of the taxexclregulationsexclequipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTAXEXCLREGULATIONSEXCLEQUIPMENT(BigDecimal value) {
        this.taxexclregulationsexclequipment = value;
    }

    /**
     * Gets the value of the factoryequipmenttotalprice property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getFACTORYEQUIPMENTTOTALPRICE() {
        return factoryequipmenttotalprice;
    }

    /**
     * Sets the value of the factoryequipmenttotalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setFACTORYEQUIPMENTTOTALPRICE(PRICEType value) {
        this.factoryequipmenttotalprice = value;
    }

    /**
     * Gets the value of the standardequipmenttotalprice property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getSTANDARDEQUIPMENTTOTALPRICE() {
        return standardequipmenttotalprice;
    }

    /**
     * Sets the value of the standardequipmenttotalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setSTANDARDEQUIPMENTTOTALPRICE(PRICEType value) {
        this.standardequipmenttotalprice = value;
    }

    /**
     * Gets the value of the importerdefineddealerequipmenttotalprice property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getIMPORTERDEFINEDDEALEREQUIPMENTTOTALPRICE() {
        return importerdefineddealerequipmenttotalprice;
    }

    /**
     * Sets the value of the importerdefineddealerequipmenttotalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setIMPORTERDEFINEDDEALEREQUIPMENTTOTALPRICE(PRICEType value) {
        this.importerdefineddealerequipmenttotalprice = value;
    }

    /**
     * Gets the value of the importerdefineddealerequipmenttotallistprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIMPORTERDEFINEDDEALEREQUIPMENTTOTALLISTPRICE() {
        return importerdefineddealerequipmenttotallistprice;
    }

    /**
     * Sets the value of the importerdefineddealerequipmenttotallistprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIMPORTERDEFINEDDEALEREQUIPMENTTOTALLISTPRICE(BigDecimal value) {
        this.importerdefineddealerequipmenttotallistprice = value;
    }

    /**
     * Gets the value of the dealerequipmenttotalprice property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getDEALEREQUIPMENTTOTALPRICE() {
        return dealerequipmenttotalprice;
    }

    /**
     * Sets the value of the dealerequipmenttotalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setDEALEREQUIPMENTTOTALPRICE(PRICEType value) {
        this.dealerequipmenttotalprice = value;
    }

    /**
     * Gets the value of the equipmentprovidedbyfactorytotalprice property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getEQUIPMENTPROVIDEDBYFACTORYTOTALPRICE() {
        return equipmentprovidedbyfactorytotalprice;
    }

    /**
     * Sets the value of the equipmentprovidedbyfactorytotalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setEQUIPMENTPROVIDEDBYFACTORYTOTALPRICE(PRICEType value) {
        this.equipmentprovidedbyfactorytotalprice = value;
    }

    /**
     * Gets the value of the equipmentprovidedbydealertotalprice property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getEQUIPMENTPROVIDEDBYDEALERTOTALPRICE() {
        return equipmentprovidedbydealertotalprice;
    }

    /**
     * Sets the value of the equipmentprovidedbydealertotalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setEQUIPMENTPROVIDEDBYDEALERTOTALPRICE(PRICEType value) {
        this.equipmentprovidedbydealertotalprice = value;
    }

    /**
     * Gets the value of the totalvehicleprice property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getTOTALVEHICLEPRICE() {
        return totalvehicleprice;
    }

    /**
     * Sets the value of the totalvehicleprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setTOTALVEHICLEPRICE(PRICEType value) {
        this.totalvehicleprice = value;
    }

    /**
     * Gets the value of the dealermarginexclequipment property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEType }
     *     
     */
    public PRICEType getDEALERMARGINEXCLEQUIPMENT() {
        return dealermarginexclequipment;
    }

    /**
     * Sets the value of the dealermarginexclequipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEType }
     *     
     */
    public void setDEALERMARGINEXCLEQUIPMENT(PRICEType value) {
        this.dealermarginexclequipment = value;
    }

    public CALCULATIONType withDEALERPRICE(BigDecimal value) {
        setDEALERPRICE(value);
        return this;
    }

    public CALCULATIONType withDEALERMARGIN(PRICEType value) {
        setDEALERMARGIN(value);
        return this;
    }

    public CALCULATIONType withSALESPRICE(PRICEType value) {
        setSALESPRICE(value);
        return this;
    }

    public CALCULATIONType withTOTALPRICE(PRICEType value) {
        setTOTALPRICE(value);
        return this;
    }

    public CALCULATIONType withVEHICLESOLDTODEALERPRICE(BigDecimal value) {
        setVEHICLESOLDTODEALERPRICE(value);
        return this;
    }

    public CALCULATIONType withVEHICLESOLDTODEALERTOTALPRICE(BigDecimal value) {
        setVEHICLESOLDTODEALERTOTALPRICE(value);
        return this;
    }

    public CALCULATIONType withCUSTOMERDISCOUNT(BigDecimal value) {
        setCUSTOMERDISCOUNT(value);
        return this;
    }

    public CALCULATIONType withGRANDTOTALPRICE(PRICEType value) {
        setGRANDTOTALPRICE(value);
        return this;
    }

    public CALCULATIONType withDEALERMAXDISCOUNT(BigDecimal value) {
        setDEALERMAXDISCOUNT(value);
        return this;
    }

    public CALCULATIONType withMINIMUMSTANDARDPRICETOTAL(PRICEType value) {
        setMINIMUMSTANDARDPRICETOTAL(value);
        return this;
    }

    public CALCULATIONType withSECURITYEQUIPMENTDISCOUNT(BigDecimal value) {
        setSECURITYEQUIPMENTDISCOUNT(value);
        return this;
    }

    public CALCULATIONType withFUELREGULATION(BigDecimal value) {
        setFUELREGULATION(value);
        return this;
    }

    public CALCULATIONType withTAXEXCLREGULATIONS(BigDecimal value) {
        setTAXEXCLREGULATIONS(value);
        return this;
    }

    public CALCULATIONType withTAXEXCLREGULATIONSEXCLEQUIPMENT(BigDecimal value) {
        setTAXEXCLREGULATIONSEXCLEQUIPMENT(value);
        return this;
    }

    public CALCULATIONType withFACTORYEQUIPMENTTOTALPRICE(PRICEType value) {
        setFACTORYEQUIPMENTTOTALPRICE(value);
        return this;
    }

    public CALCULATIONType withSTANDARDEQUIPMENTTOTALPRICE(PRICEType value) {
        setSTANDARDEQUIPMENTTOTALPRICE(value);
        return this;
    }

    public CALCULATIONType withIMPORTERDEFINEDDEALEREQUIPMENTTOTALPRICE(PRICEType value) {
        setIMPORTERDEFINEDDEALEREQUIPMENTTOTALPRICE(value);
        return this;
    }

    public CALCULATIONType withIMPORTERDEFINEDDEALEREQUIPMENTTOTALLISTPRICE(BigDecimal value) {
        setIMPORTERDEFINEDDEALEREQUIPMENTTOTALLISTPRICE(value);
        return this;
    }

    public CALCULATIONType withDEALEREQUIPMENTTOTALPRICE(PRICEType value) {
        setDEALEREQUIPMENTTOTALPRICE(value);
        return this;
    }

    public CALCULATIONType withEQUIPMENTPROVIDEDBYFACTORYTOTALPRICE(PRICEType value) {
        setEQUIPMENTPROVIDEDBYFACTORYTOTALPRICE(value);
        return this;
    }

    public CALCULATIONType withEQUIPMENTPROVIDEDBYDEALERTOTALPRICE(PRICEType value) {
        setEQUIPMENTPROVIDEDBYDEALERTOTALPRICE(value);
        return this;
    }

    public CALCULATIONType withTOTALVEHICLEPRICE(PRICEType value) {
        setTOTALVEHICLEPRICE(value);
        return this;
    }

    public CALCULATIONType withDEALERMARGINEXCLEQUIPMENT(PRICEType value) {
        setDEALERMARGINEXCLEQUIPMENT(value);
        return this;
    }

}
