//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 12:09:56 PM PKT 
//


package dk.semler.ws.vehiclesalecalculator.v201412.calculatenewvehicle.response;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				CODE - DESCRIPTION
 * 				1200    Vehicle {VEHICLEID=String} does not exist                             
 * 				1201    Taxcode {TAXCODE=String} does not exist                               
 * 				1202    Price for Equipment or Color is missing in Autocore {MKDE=String}     
 * 				1203    Price for model / pricecode is missing in Autovore {COA815F=String}   
 * 				1204    PRNO {MKDE=String} is illegal                                         
 * 				1205    dealer profit may not be negative                              
 * 				1206    Rabat is too large, may not be higher than max. dealer profit {DEALERMAXDISCOUNT=String}  
 * 				1207    upholstery text does not exist 	
 *                                 1257    More than 60 Equipment/color codes			
 * 			
 * 
 * <p>Java class for ErrorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ErrorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TRANSACTIONID"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="13"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CODE"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="5"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DATA" type="{}ErrorDataType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErrorType", propOrder = {
    "transactionid",
    "code",
    "description",
    "data"
})
public class ErrorType {

    @XmlElement(name = "TRANSACTIONID", required = true)
    protected String transactionid;
    @XmlElement(name = "CODE", required = true)
    protected String code;
    @XmlElement(name = "DESCRIPTION", required = true)
    protected String description;
    @XmlElement(name = "DATA")
    protected List<ErrorDataType> data;

    /**
     * Gets the value of the transactionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSACTIONID() {
        return transactionid;
    }

    /**
     * Sets the value of the transactionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSACTIONID(String value) {
        this.transactionid = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODE() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODE(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDATA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorDataType }
     * 
     * 
     */
    public List<ErrorDataType> getDATA() {
        if (data == null) {
            data = new ArrayList<ErrorDataType>();
        }
        return this.data;
    }

    public ErrorType withTRANSACTIONID(String value) {
        setTRANSACTIONID(value);
        return this;
    }

    public ErrorType withCODE(String value) {
        setCODE(value);
        return this;
    }

    public ErrorType withDESCRIPTION(String value) {
        setDESCRIPTION(value);
        return this;
    }

    public ErrorType withDATA(ErrorDataType... values) {
        if (values!= null) {
            for (ErrorDataType value: values) {
                getDATA().add(value);
            }
        }
        return this;
    }

    public ErrorType withDATA(Collection<ErrorDataType> values) {
        if (values!= null) {
            getDATA().addAll(values);
        }
        return this;
    }

}
