//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 12:09:56 PM PKT 
//


package dk.semler.ws.vehiclesalecalculator.v201412.calculatenewvehicle.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.semler.ws.vehiclesalecalculator.v201412.calculatenewvehicle.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.semler.ws.vehiclesalecalculator.v201412.calculatenewvehicle.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MESSAGE }
     * 
     */
    public MESSAGE createMESSAGE() {
        return new MESSAGE();
    }

    /**
     * Create an instance of {@link MESSAGE.RESPONSE }
     * 
     */
    public MESSAGE.RESPONSE createMESSAGERESPONSE() {
        return new MESSAGE.RESPONSE();
    }

    /**
     * Create an instance of {@link ErrorDataType }
     * 
     */
    public ErrorDataType createErrorDataType() {
        return new ErrorDataType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link VEHICLEType }
     * 
     */
    public VEHICLEType createVEHICLEType() {
        return new VEHICLEType();
    }

    /**
     * Create an instance of {@link CALCULATIONType }
     * 
     */
    public CALCULATIONType createCALCULATIONType() {
        return new CALCULATIONType();
    }

    /**
     * Create an instance of {@link FACTORYEQUIPMENTType }
     * 
     */
    public FACTORYEQUIPMENTType createFACTORYEQUIPMENTType() {
        return new FACTORYEQUIPMENTType();
    }

    /**
     * Create an instance of {@link PRICEType }
     * 
     */
    public PRICEType createPRICEType() {
        return new PRICEType();
    }

}
