//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 12:09:56 PM PKT 
//


package dk.semler.ws.vehiclesalecalculator.v201412.calculatenewvehicle.response;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			
 * 			
 * 
 * <p>Java class for VEHICLEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VEHICLEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="COLORTEXT" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="40"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="INTERIORTEXT" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="40"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FUELTYPE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="BENZIN"/&gt;
 *               &lt;enumeration value="DIESEL"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="KILOMETERSPERLITER" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="5"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TAXCODE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FACTORYEQUIPMENT" type="{}FACTORYEQUIPMENTType" maxOccurs="61" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VEHICLEType", propOrder = {
    "colortext",
    "interiortext",
    "fueltype",
    "kilometersperliter",
    "taxcode",
    "factoryequipment"
})
public class VEHICLEType {

    @XmlElement(name = "COLORTEXT")
    protected String colortext;
    @XmlElement(name = "INTERIORTEXT")
    protected String interiortext;
    @XmlElement(name = "FUELTYPE")
    protected String fueltype;
    @XmlElement(name = "KILOMETERSPERLITER")
    protected BigDecimal kilometersperliter;
    @XmlElement(name = "TAXCODE")
    protected String taxcode;
    @XmlElement(name = "FACTORYEQUIPMENT")
    protected List<FACTORYEQUIPMENTType> factoryequipment;

    /**
     * Gets the value of the colortext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOLORTEXT() {
        return colortext;
    }

    /**
     * Sets the value of the colortext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOLORTEXT(String value) {
        this.colortext = value;
    }

    /**
     * Gets the value of the interiortext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTERIORTEXT() {
        return interiortext;
    }

    /**
     * Sets the value of the interiortext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTERIORTEXT(String value) {
        this.interiortext = value;
    }

    /**
     * Gets the value of the fueltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFUELTYPE() {
        return fueltype;
    }

    /**
     * Sets the value of the fueltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFUELTYPE(String value) {
        this.fueltype = value;
    }

    /**
     * Gets the value of the kilometersperliter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKILOMETERSPERLITER() {
        return kilometersperliter;
    }

    /**
     * Sets the value of the kilometersperliter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKILOMETERSPERLITER(BigDecimal value) {
        this.kilometersperliter = value;
    }

    /**
     * Gets the value of the taxcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXCODE() {
        return taxcode;
    }

    /**
     * Sets the value of the taxcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXCODE(String value) {
        this.taxcode = value;
    }

    /**
     * Gets the value of the factoryequipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the factoryequipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFACTORYEQUIPMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FACTORYEQUIPMENTType }
     * 
     * 
     */
    public List<FACTORYEQUIPMENTType> getFACTORYEQUIPMENT() {
        if (factoryequipment == null) {
            factoryequipment = new ArrayList<FACTORYEQUIPMENTType>();
        }
        return this.factoryequipment;
    }

    public VEHICLEType withCOLORTEXT(String value) {
        setCOLORTEXT(value);
        return this;
    }

    public VEHICLEType withINTERIORTEXT(String value) {
        setINTERIORTEXT(value);
        return this;
    }

    public VEHICLEType withFUELTYPE(String value) {
        setFUELTYPE(value);
        return this;
    }

    public VEHICLEType withKILOMETERSPERLITER(BigDecimal value) {
        setKILOMETERSPERLITER(value);
        return this;
    }

    public VEHICLEType withTAXCODE(String value) {
        setTAXCODE(value);
        return this;
    }

    public VEHICLEType withFACTORYEQUIPMENT(FACTORYEQUIPMENTType... values) {
        if (values!= null) {
            for (FACTORYEQUIPMENTType value: values) {
                getFACTORYEQUIPMENT().add(value);
            }
        }
        return this;
    }

    public VEHICLEType withFACTORYEQUIPMENT(Collection<FACTORYEQUIPMENTType> values) {
        if (values!= null) {
            getFACTORYEQUIPMENT().addAll(values);
        }
        return this;
    }

}
