//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 12:09:26 PM PKT 
//


package dk.semler.ws.vehiclesalecalculator.v201412.calculatenewvehicle.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Describes how the calculation is to be performed
 * 			
 * 
 * <p>Java class for CALCULATIONTYPEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CALCULATIONTYPEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CALCULATIONTYPE"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="CAR_INCL_VAT_INCL_TAX"/&gt;
 *               &lt;enumeration value="CAR_EXCL_VAT_EXCL_TAX"/&gt;
 *               &lt;enumeration value="CAR_INCL_VAT_EXCL_TAX"/&gt;
 *               &lt;enumeration value="CAR_EXCL_VAT_INCL_TAX"/&gt;
 *               &lt;enumeration value="VAN_INCL_VAT_INCL_TAX"/&gt;
 *               &lt;enumeration value="VAN_EXCL_VAT_EXCL_TAX"/&gt;
 *               &lt;enumeration value="VAN_EXCL_VAT_INCL_TAX"/&gt;
 *               &lt;enumeration value="VAN_INCL_VAT_EXCL_TAX"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TAXCODE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OVERRIDE" type="{}OVERRIDEType" minOccurs="0"/&gt;
 *         &lt;element name="EXCLUDEAUTOMATICSEARCHOFSTANDARDEQUIPMENT" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EXCLUDEAUTOMATICSEARCHOFPLUSPACKAGES" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CALCULATIONTYPEType", propOrder = {
    "calculationtype",
    "taxcode",
    "override",
    "excludeautomaticsearchofstandardequipment",
    "excludeautomaticsearchofpluspackages"
})
public class CALCULATIONTYPEType {

    @XmlElement(name = "CALCULATIONTYPE", required = true)
    protected String calculationtype;
    @XmlElement(name = "TAXCODE")
    protected String taxcode;
    @XmlElement(name = "OVERRIDE")
    protected OVERRIDEType override;
    @XmlElement(name = "EXCLUDEAUTOMATICSEARCHOFSTANDARDEQUIPMENT", defaultValue = "false")
    protected boolean excludeautomaticsearchofstandardequipment;
    @XmlElement(name = "EXCLUDEAUTOMATICSEARCHOFPLUSPACKAGES", defaultValue = "false")
    protected boolean excludeautomaticsearchofpluspackages;

    /**
     * Gets the value of the calculationtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCALCULATIONTYPE() {
        return calculationtype;
    }

    /**
     * Sets the value of the calculationtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCALCULATIONTYPE(String value) {
        this.calculationtype = value;
    }

    /**
     * Gets the value of the taxcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXCODE() {
        return taxcode;
    }

    /**
     * Sets the value of the taxcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXCODE(String value) {
        this.taxcode = value;
    }

    /**
     * Gets the value of the override property.
     * 
     * @return
     *     possible object is
     *     {@link OVERRIDEType }
     *     
     */
    public OVERRIDEType getOVERRIDE() {
        return override;
    }

    /**
     * Sets the value of the override property.
     * 
     * @param value
     *     allowed object is
     *     {@link OVERRIDEType }
     *     
     */
    public void setOVERRIDE(OVERRIDEType value) {
        this.override = value;
    }

    /**
     * Gets the value of the excludeautomaticsearchofstandardequipment property.
     * 
     */
    public boolean isEXCLUDEAUTOMATICSEARCHOFSTANDARDEQUIPMENT() {
        return excludeautomaticsearchofstandardequipment;
    }

    /**
     * Sets the value of the excludeautomaticsearchofstandardequipment property.
     * 
     */
    public void setEXCLUDEAUTOMATICSEARCHOFSTANDARDEQUIPMENT(boolean value) {
        this.excludeautomaticsearchofstandardequipment = value;
    }

    /**
     * Gets the value of the excludeautomaticsearchofpluspackages property.
     * 
     */
    public boolean isEXCLUDEAUTOMATICSEARCHOFPLUSPACKAGES() {
        return excludeautomaticsearchofpluspackages;
    }

    /**
     * Sets the value of the excludeautomaticsearchofpluspackages property.
     * 
     */
    public void setEXCLUDEAUTOMATICSEARCHOFPLUSPACKAGES(boolean value) {
        this.excludeautomaticsearchofpluspackages = value;
    }

    public CALCULATIONTYPEType withCALCULATIONTYPE(String value) {
        setCALCULATIONTYPE(value);
        return this;
    }

    public CALCULATIONTYPEType withTAXCODE(String value) {
        setTAXCODE(value);
        return this;
    }

    public CALCULATIONTYPEType withOVERRIDE(OVERRIDEType value) {
        setOVERRIDE(value);
        return this;
    }

    public CALCULATIONTYPEType withEXCLUDEAUTOMATICSEARCHOFSTANDARDEQUIPMENT(boolean value) {
        setEXCLUDEAUTOMATICSEARCHOFSTANDARDEQUIPMENT(value);
        return this;
    }

    public CALCULATIONTYPEType withEXCLUDEAUTOMATICSEARCHOFPLUSPACKAGES(boolean value) {
        setEXCLUDEAUTOMATICSEARCHOFPLUSPACKAGES(value);
        return this;
    }

}
