//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 12:09:26 PM PKT 
//


package dk.semler.ws.vehiclesalecalculator.v201412.calculatenewvehicle.request;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Describes the fields which can be overridden by the consumer
 * 			
 * 
 * <p>Java class for OVERRIDEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OVERRIDEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="KILOMETERSPERLITER" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="5"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OVERRIDEType", propOrder = {
    "kilometersperliter"
})
public class OVERRIDEType {

    @XmlElement(name = "KILOMETERSPERLITER")
    protected BigDecimal kilometersperliter;

    /**
     * Gets the value of the kilometersperliter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKILOMETERSPERLITER() {
        return kilometersperliter;
    }

    /**
     * Sets the value of the kilometersperliter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKILOMETERSPERLITER(BigDecimal value) {
        this.kilometersperliter = value;
    }

    public OVERRIDEType withKILOMETERSPERLITER(BigDecimal value) {
        setKILOMETERSPERLITER(value);
        return this;
    }

}
