//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 12:09:26 PM PKT 
//


package dk.semler.ws.vehiclesalecalculator.v201412.calculatenewvehicle.request;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 * 				Basic vehicle information. 
 * 			
 * 
 * <p>Java class for VEHICLEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VEHICLEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MODELCODE"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MODELYEAR" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="PRICECODE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="COLORCODE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="INTERIORCODE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DOORS" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="PRNO" maxOccurs="60" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;productNumberType"&gt;
 *                 &lt;attribute name="PRNOTYPE"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;enumeration value="CNF"/&gt;
 *                       &lt;enumeration value="EQP"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FACTORYEQUIPMENT" maxOccurs="60" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EXCLUDEDSTANDARDEQUIPMENT" maxOccurs="10" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DEALEREQUIPMENT" type="{}DEALEREQUIPMENTType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VEHICLEType", propOrder = {
    "modelcode",
    "modelyear",
    "pricecode",
    "colorcode",
    "interiorcode",
    "doors",
    "prno",
    "factoryequipment",
    "excludedstandardequipment",
    "dealerequipment"
})
public class VEHICLEType {

    @XmlElement(name = "MODELCODE", required = true)
    protected String modelcode;
    @XmlElement(name = "MODELYEAR")
    protected int modelyear;
    @XmlElement(name = "PRICECODE")
    protected String pricecode;
    @XmlElement(name = "COLORCODE")
    protected String colorcode;
    @XmlElement(name = "INTERIORCODE")
    protected String interiorcode;
    @XmlElement(name = "DOORS")
    protected Integer doors;
    @XmlElement(name = "PRNO")
    protected List<VEHICLEType.PRNO> prno;
    @XmlElement(name = "FACTORYEQUIPMENT")
    protected List<String> factoryequipment;
    @XmlElement(name = "EXCLUDEDSTANDARDEQUIPMENT")
    protected List<String> excludedstandardequipment;
    @XmlElement(name = "DEALEREQUIPMENT")
    protected List<DEALEREQUIPMENTType> dealerequipment;

    /**
     * Gets the value of the modelcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMODELCODE() {
        return modelcode;
    }

    /**
     * Sets the value of the modelcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMODELCODE(String value) {
        this.modelcode = value;
    }

    /**
     * Gets the value of the modelyear property.
     * 
     */
    public int getMODELYEAR() {
        return modelyear;
    }

    /**
     * Sets the value of the modelyear property.
     * 
     */
    public void setMODELYEAR(int value) {
        this.modelyear = value;
    }

    /**
     * Gets the value of the pricecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRICECODE() {
        return pricecode;
    }

    /**
     * Sets the value of the pricecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRICECODE(String value) {
        this.pricecode = value;
    }

    /**
     * Gets the value of the colorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOLORCODE() {
        return colorcode;
    }

    /**
     * Sets the value of the colorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOLORCODE(String value) {
        this.colorcode = value;
    }

    /**
     * Gets the value of the interiorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTERIORCODE() {
        return interiorcode;
    }

    /**
     * Sets the value of the interiorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTERIORCODE(String value) {
        this.interiorcode = value;
    }

    /**
     * Gets the value of the doors property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDOORS() {
        return doors;
    }

    /**
     * Sets the value of the doors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDOORS(Integer value) {
        this.doors = value;
    }

    /**
     * Gets the value of the prno property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prno property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRNO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VEHICLEType.PRNO }
     * 
     * 
     */
    public List<VEHICLEType.PRNO> getPRNO() {
        if (prno == null) {
            prno = new ArrayList<VEHICLEType.PRNO>();
        }
        return this.prno;
    }

    /**
     * Gets the value of the factoryequipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the factoryequipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFACTORYEQUIPMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFACTORYEQUIPMENT() {
        if (factoryequipment == null) {
            factoryequipment = new ArrayList<String>();
        }
        return this.factoryequipment;
    }

    /**
     * Gets the value of the excludedstandardequipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the excludedstandardequipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXCLUDEDSTANDARDEQUIPMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEXCLUDEDSTANDARDEQUIPMENT() {
        if (excludedstandardequipment == null) {
            excludedstandardequipment = new ArrayList<String>();
        }
        return this.excludedstandardequipment;
    }

    /**
     * Gets the value of the dealerequipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dealerequipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDEALEREQUIPMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DEALEREQUIPMENTType }
     * 
     * 
     */
    public List<DEALEREQUIPMENTType> getDEALEREQUIPMENT() {
        if (dealerequipment == null) {
            dealerequipment = new ArrayList<DEALEREQUIPMENTType>();
        }
        return this.dealerequipment;
    }

    public VEHICLEType withMODELCODE(String value) {
        setMODELCODE(value);
        return this;
    }

    public VEHICLEType withMODELYEAR(int value) {
        setMODELYEAR(value);
        return this;
    }

    public VEHICLEType withPRICECODE(String value) {
        setPRICECODE(value);
        return this;
    }

    public VEHICLEType withCOLORCODE(String value) {
        setCOLORCODE(value);
        return this;
    }

    public VEHICLEType withINTERIORCODE(String value) {
        setINTERIORCODE(value);
        return this;
    }

    public VEHICLEType withDOORS(Integer value) {
        setDOORS(value);
        return this;
    }

    public VEHICLEType withPRNO(VEHICLEType.PRNO... values) {
        if (values!= null) {
            for (VEHICLEType.PRNO value: values) {
                getPRNO().add(value);
            }
        }
        return this;
    }

    public VEHICLEType withPRNO(Collection<VEHICLEType.PRNO> values) {
        if (values!= null) {
            getPRNO().addAll(values);
        }
        return this;
    }

    public VEHICLEType withFACTORYEQUIPMENT(String... values) {
        if (values!= null) {
            for (String value: values) {
                getFACTORYEQUIPMENT().add(value);
            }
        }
        return this;
    }

    public VEHICLEType withFACTORYEQUIPMENT(Collection<String> values) {
        if (values!= null) {
            getFACTORYEQUIPMENT().addAll(values);
        }
        return this;
    }

    public VEHICLEType withEXCLUDEDSTANDARDEQUIPMENT(String... values) {
        if (values!= null) {
            for (String value: values) {
                getEXCLUDEDSTANDARDEQUIPMENT().add(value);
            }
        }
        return this;
    }

    public VEHICLEType withEXCLUDEDSTANDARDEQUIPMENT(Collection<String> values) {
        if (values!= null) {
            getEXCLUDEDSTANDARDEQUIPMENT().addAll(values);
        }
        return this;
    }

    public VEHICLEType withDEALEREQUIPMENT(DEALEREQUIPMENTType... values) {
        if (values!= null) {
            for (DEALEREQUIPMENTType value: values) {
                getDEALEREQUIPMENT().add(value);
            }
        }
        return this;
    }

    public VEHICLEType withDEALEREQUIPMENT(Collection<DEALEREQUIPMENTType> values) {
        if (values!= null) {
            getDEALEREQUIPMENT().addAll(values);
        }
        return this;
    }


    /**
     * Only valid PR Numbers (equipment codes and configuration codes).
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;&gt;productNumberType"&gt;
     *       &lt;attribute name="PRNOTYPE"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="CNF"/&gt;
     *             &lt;enumeration value="EQP"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PRNO {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "PRNOTYPE")
        protected String prnotype;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the prnotype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPRNOTYPE() {
            return prnotype;
        }

        /**
         * Sets the value of the prnotype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPRNOTYPE(String value) {
            this.prnotype = value;
        }

        public VEHICLEType.PRNO withValue(String value) {
            setValue(value);
            return this;
        }

        public VEHICLEType.PRNO withPRNOTYPE(String value) {
            setPRNOTYPE(value);
            return this;
        }

    }

}
