//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.01 at 11:12:38 PM PKT 
//


package dk.semler.ws.vehiclesalecalculator.v201412.calculateusedvehicle.request;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			
 * 			
 * 
 * <p>Java class for ECONOMYType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ECONOMYType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VEHICLESALEPRICE"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EXTRAEQUIPMENTPRICE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ADDITIONALAMOUNT" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DELIVERYEXPENSES"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LICENSETAGFEE"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CASHONDELIVERY" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DOWNPAYMENT" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="11"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DEALEREQUIPMENT" type="{}DEALEREQUIPMENTType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ECONOMYType", propOrder = {
    "vehiclesaleprice",
    "extraequipmentprice",
    "additionalamount",
    "deliveryexpenses",
    "licensetagfee",
    "cashondelivery",
    "downpayment",
    "dealerequipment"
})
public class ECONOMYType {

    @XmlElement(name = "VEHICLESALEPRICE", required = true)
    protected BigDecimal vehiclesaleprice;
    @XmlElement(name = "EXTRAEQUIPMENTPRICE")
    protected BigDecimal extraequipmentprice;
    @XmlElement(name = "ADDITIONALAMOUNT")
    protected List<BigDecimal> additionalamount;
    @XmlElement(name = "DELIVERYEXPENSES", required = true)
    protected BigDecimal deliveryexpenses;
    @XmlElement(name = "LICENSETAGFEE", required = true)
    protected BigDecimal licensetagfee;
    @XmlElement(name = "CASHONDELIVERY")
    protected BigDecimal cashondelivery;
    @XmlElement(name = "DOWNPAYMENT")
    protected BigDecimal downpayment;
    @XmlElement(name = "DEALEREQUIPMENT")
    protected List<DEALEREQUIPMENTType> dealerequipment;

    /**
     * Gets the value of the vehiclesaleprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVEHICLESALEPRICE() {
        return vehiclesaleprice;
    }

    /**
     * Sets the value of the vehiclesaleprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVEHICLESALEPRICE(BigDecimal value) {
        this.vehiclesaleprice = value;
    }

    /**
     * Gets the value of the extraequipmentprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEXTRAEQUIPMENTPRICE() {
        return extraequipmentprice;
    }

    /**
     * Sets the value of the extraequipmentprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEXTRAEQUIPMENTPRICE(BigDecimal value) {
        this.extraequipmentprice = value;
    }

    /**
     * Gets the value of the additionalamount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalamount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADDITIONALAMOUNT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getADDITIONALAMOUNT() {
        if (additionalamount == null) {
            additionalamount = new ArrayList<BigDecimal>();
        }
        return this.additionalamount;
    }

    /**
     * Gets the value of the deliveryexpenses property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDELIVERYEXPENSES() {
        return deliveryexpenses;
    }

    /**
     * Sets the value of the deliveryexpenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDELIVERYEXPENSES(BigDecimal value) {
        this.deliveryexpenses = value;
    }

    /**
     * Gets the value of the licensetagfee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLICENSETAGFEE() {
        return licensetagfee;
    }

    /**
     * Sets the value of the licensetagfee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLICENSETAGFEE(BigDecimal value) {
        this.licensetagfee = value;
    }

    /**
     * Gets the value of the cashondelivery property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCASHONDELIVERY() {
        return cashondelivery;
    }

    /**
     * Sets the value of the cashondelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCASHONDELIVERY(BigDecimal value) {
        this.cashondelivery = value;
    }

    /**
     * Gets the value of the downpayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDOWNPAYMENT() {
        return downpayment;
    }

    /**
     * Sets the value of the downpayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDOWNPAYMENT(BigDecimal value) {
        this.downpayment = value;
    }

    /**
     * Gets the value of the dealerequipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dealerequipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDEALEREQUIPMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DEALEREQUIPMENTType }
     * 
     * 
     */
    public List<DEALEREQUIPMENTType> getDEALEREQUIPMENT() {
        if (dealerequipment == null) {
            dealerequipment = new ArrayList<DEALEREQUIPMENTType>();
        }
        return this.dealerequipment;
    }

    public ECONOMYType withVEHICLESALEPRICE(BigDecimal value) {
        setVEHICLESALEPRICE(value);
        return this;
    }

    public ECONOMYType withEXTRAEQUIPMENTPRICE(BigDecimal value) {
        setEXTRAEQUIPMENTPRICE(value);
        return this;
    }

    public ECONOMYType withADDITIONALAMOUNT(BigDecimal... values) {
        if (values!= null) {
            for (BigDecimal value: values) {
                getADDITIONALAMOUNT().add(value);
            }
        }
        return this;
    }

    public ECONOMYType withADDITIONALAMOUNT(Collection<BigDecimal> values) {
        if (values!= null) {
            getADDITIONALAMOUNT().addAll(values);
        }
        return this;
    }

    public ECONOMYType withDELIVERYEXPENSES(BigDecimal value) {
        setDELIVERYEXPENSES(value);
        return this;
    }

    public ECONOMYType withLICENSETAGFEE(BigDecimal value) {
        setLICENSETAGFEE(value);
        return this;
    }

    public ECONOMYType withCASHONDELIVERY(BigDecimal value) {
        setCASHONDELIVERY(value);
        return this;
    }

    public ECONOMYType withDOWNPAYMENT(BigDecimal value) {
        setDOWNPAYMENT(value);
        return this;
    }

    public ECONOMYType withDEALEREQUIPMENT(DEALEREQUIPMENTType... values) {
        if (values!= null) {
            for (DEALEREQUIPMENTType value: values) {
                getDEALEREQUIPMENT().add(value);
            }
        }
        return this;
    }

    public ECONOMYType withDEALEREQUIPMENT(Collection<DEALEREQUIPMENTType> values) {
        if (values!= null) {
            getDEALEREQUIPMENT().addAll(values);
        }
        return this;
    }

}
