//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.01 at 11:12:38 PM PKT 
//


package dk.semler.ws.vehiclesalecalculator.v201412.calculateusedvehicle.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.semler.ws.vehiclesalecalculator.v201412.calculateusedvehicle.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.semler.ws.vehiclesalecalculator.v201412.calculateusedvehicle.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MESSAGE }
     * 
     */
    public MESSAGE createMESSAGE() {
        return new MESSAGE();
    }

    /**
     * Create an instance of {@link MESSAGE.REQUEST }
     * 
     */
    public MESSAGE.REQUEST createMESSAGEREQUEST() {
        return new MESSAGE.REQUEST();
    }

    /**
     * Create an instance of {@link DEALEREQUIPMENTType }
     * 
     */
    public DEALEREQUIPMENTType createDEALEREQUIPMENTType() {
        return new DEALEREQUIPMENTType();
    }

    /**
     * Create an instance of {@link VEHICLESOLDTODEALERType }
     * 
     */
    public VEHICLESOLDTODEALERType createVEHICLESOLDTODEALERType() {
        return new VEHICLESOLDTODEALERType();
    }

    /**
     * Create an instance of {@link ECONOMYType }
     * 
     */
    public ECONOMYType createECONOMYType() {
        return new ECONOMYType();
    }

}
